// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUwxEkSO4trvafLc9duFirUAxAwTAzr_8',
    appId: '1:1052976584219:web:697d26b3cb4b05823bcabe',
    messagingSenderId: '1052976584219',
    projectId: 'service-provider-2798f',
    authDomain: 'service-provider-2798f.firebaseapp.com',
    storageBucket: 'service-provider-2798f.appspot.com',
    measurementId: 'G-N985DKL7NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIX-8a5srmdhL9pEg4Erbc9P6HBzGGNdU',
    appId: '1:1052976584219:android:502c20b8d542e7d53bcabe',
    messagingSenderId: '1052976584219',
    projectId: 'service-provider-2798f',
    storageBucket: 'service-provider-2798f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC13OhpxBttDh6QuQWTinxUbEJzlkQ3usw',
    appId: '1:1052976584219:ios:1264ef96c087c4463bcabe',
    messagingSenderId: '1052976584219',
    projectId: 'service-provider-2798f',
    storageBucket: 'service-provider-2798f.appspot.com',
    iosBundleId: 'com.example.serviceProvider',
  );
}
